# Generated by Django 6.0.2 on 2026-03-02 03:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_author_id_alter_comment_id_alter_entry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
