# Generated by Django 6.0.2 on 2026-03-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_author_id_alter_comment_id_alter_entry_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrequest',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='followrequest',
            name='target',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REQUESTING', 'Requesting'), ('REJECTED', 'Rejected')], default='REQUESTED'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('actor', models.F('target')), _negated=True), name='restrict_self_follow'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('actor', 'target'), name='unique_follow'),
        ),
        migrations.DeleteModel(
            name='FollowRequest',
        ),
    ]
