# Generated by Django 6.0.2 on 2026-03-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entry_serial'),
        ('core', '0008_remove_followrequest_actor_and_more'),
    ]

    operations = [
    ]
