# Generated by Django 6.0.2 on 2026-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20260302_0419"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="github",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="author",
            name="profileImage",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="author",
            name="web",
            field=models.URLField(blank=True, default=""),
        ),
    ]
