# Generated by Django 6.0.2 on 2026-03-14 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comment_content_type_commentlike_entrylike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
