# Generated by Django 6.0.2 on 2026-03-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_like_serials_and_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
