# Generated by Django 6.0.2 on 2026-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_entry_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="profileImage",
            field=models.URLField(blank=True, default="https://placehold.co/600x400"),
        ),
    ]
