# Generated by Django 6.0.2 on 2026-03-22 06:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=core.models.get_image_upload_path),
        ),
    ]
