# Generated by Django 6.0.2 on 2026-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remotenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='web',
            field=models.URLField(blank=True, default=''),
        ),
    ]
