# Generated by Django 6.0.2 on 2026-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_entry_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='displayName',
            field=models.CharField(max_length=32),
        ),
    ]
