# Generated by Django 6.0.2 on 2026-03-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_author_displayname"),
        ("core", "0023_inboxevent"),
    ]

    operations = []
