# Generated by Django 6.0.2 on 2026-03-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_merge_0023_alter_author_displayname_0023_inboxevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("REQUESTED", "Requested"),
                    ("REJECTED", "Rejected"),
                ],
                default="REQUESTED",
            ),
        ),
    ]
